FROM centos:centos7
MAINTAINER radicalshu weishu.ops@gmail.com

ADD . /src
# setup sshd
RUN yum install -y openssh-server openssh-clients  epel-release
RUN echo 'root:87654312**.0' | chpasswd
RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

## Suppress error message 'Could not load host key: ...'
RUN /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
RUN /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''
EXPOSE 22


# setup supervisor
RUN yum install -y supervisor
RUN cat /src/Supervisorfile >> /etc/supervisord.conf


CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"] 
