FROM centos:centos7
MAINTAINER radicalshu weishu.ops@gmail.com

ADD . /src
# setup sshd
RUN yum install -y openssh-server openssh-clients  epel-release
RUN echo 'root:87654312' | chpasswd  #change your own password here
RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

## Suppress error message 'Could not load host key: ...'
RUN /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
RUN /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''
EXPOSE 22

## setup  nginx
RUN yum install -y nginx
RUN cat /src/nginx.conf > /etc/nginx/nginx.conf
RUN cat /src/down.conf > /etc/nginx/conf.d/down.conf
RUN cat /src/blog.conf > /etc/nginx/conf.d/blog.conf
EXPOSE 80

# setup supervisor
RUN yum install -y supervisor
RUN cat /src/Supervisorfile >> /etc/supervisord.conf

# add the VOLUME for download site
VOLUME ["/opt/down"]

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"] 
